config/routes.rb
Rails.application.routes.draw do
  resources :flats
  root "flats#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
  <a class="navbar-brand mx-2" href="/flats">Simple Airbnb</a>
  <%= link_to 'Add flat', new_flat_path, class: 'btn btn-primary mx-3' %>
</nav>
</div>
<h1>All our Flats</h1> <br>


<div class="container">
  <% @flats.each do |flat| %>
    <div class="card align-items-center col-sm-3 mb-3 mx-1 mb-sm-0 ">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-name"><%= flat.name %></h5>
        <p class="card-address"><%= flat.address %></p>
          <p><%= flat.price_per_night %></p>
          <p><%= flat.number_of_guests %></p>
        <%= link_to 'More info', flat, class: 'btn btn-info' %>
        <%= link_to 'Edit', edit_flat_path(flat), class: 'btn btn-warning' %>
        <%= link_to 'Remove', flat, method: :delete, data: { confirm: 'Are you sure ?' }, class: 'btn btn-danger' %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>